<?php
/**
 * Created by PhpStorm.
 * User: Iriven France
 * Date: 03/06/2018
 * Time: 21:21
 */

namespace Iriven\Plugins\Form\Elements;


class Country extends Select
{
    private $CountriesDatas = [
        ['code' => 'AF', 'name' => 'Afghanistan', 'native' => 'غانستان'],
        ['code' => 'AX', 'name' => 'Åland Islands', 'native' => 'Åland'],
        ['code' => 'AL', 'name' => 'Albania', 'native' => 'Shqipëri'],
        ['code' => 'DZ', 'name' => 'Algeria', 'native' => 'الجزائر'],
        ['code' => 'AS', 'name' => 'American Samoa', 'native' => ''],
        ['code' => 'AD', 'name' => 'Andorra', 'native' => ''],
        ['code' => 'AO', 'name' => 'Angola', 'native' => ''],
        ['code' => 'AI', 'name' => 'Anguilla', 'native' => ''],
        ['code' => 'AQ', 'name' => 'Antarctica', 'native' => ''],
        ['code' => 'AG', 'name' => 'Antigua and Barbuda', 'native' => ''],
        ['code' => 'AR', 'name' => 'Argentina', 'native' => ''],
        ['code' => 'AM', 'name' => 'Armenia', 'native' => 'Հայաստան'],
        ['code' => 'AW', 'name' => 'Aruba', 'native' => ''],
        ['code' => 'AC', 'name' => 'Ascension Island', 'native' => ''],
        ['code' => 'AU', 'name' => 'Australia', 'native' => ''],
        ['code' => 'AT', 'name' => 'Austria', 'native' => 'Österreich'],
        ['code' => 'AZ', 'name' => 'Azerbaijan', 'native' => 'Azərbaycan'],
        ['code' => 'BS', 'name' => 'Bahamas', 'native' => ''],
        ['code' => 'BH', 'name' => 'Bahrain', 'native' => 'البحرين'],
        ['code' => 'BD', 'name' => 'Bangladesh', 'native' => 'বাংলাদেশ'],
        ['code' => 'BB', 'name' => 'Barbados', 'native' => ''],
        ['code' => 'BY', 'name' => 'Belarus', 'native' => 'Беларусь'],
        ['code' => 'BE', 'name' => 'Belgium', 'native' => 'België'],
        ['code' => 'BZ', 'name' => 'Belize', 'native' => ''],
        ['code' => 'BJ', 'name' => 'Benin', 'native' => 'Bénin'],
        ['code' => 'BM', 'name' => 'Bermuda', 'native' => ''],
        ['code' => 'BT', 'name' => 'Bhutan', 'native' => 'འབྲུག'],
        ['code' => 'BO', 'name' => 'Bolivia', 'native' => ''],
        ['code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'native' => 'Босна и Херцеговина'],
        ['code' => 'BW', 'name' => 'Botswana', 'native' => ''],
        ['code' => 'BV', 'name' => 'Bouvet Island', 'native' => ''],
        ['code' => 'BR', 'name' => 'Brazil', 'native' => 'Brasil'],
        ['code' => 'IO', 'name' => 'British Indian Ocean Territory', 'native' => ''],
        ['code' => 'VG', 'name' => 'British Virgin Islands', 'native' => ''],
        ['code' => 'BN', 'name' => 'Brunei', 'native' => ''],
        ['code' => 'BG', 'name' => 'Bulgaria', 'native' => 'България'],
        ['code' => 'BF', 'name' => 'Burkina Faso', 'native' => ''],
        ['code' => 'BI', 'name' => 'Burundi', 'native' => 'Uburundi'],
        ['code' => 'KH', 'name' => 'Cambodia', 'native' => 'កម្ពុជា'],
        ['code' => 'CM', 'name' => 'Cameroon', 'native' => 'Cameroun'],
        ['code' => 'CA', 'name' => 'Canada', 'native' => ''],
        ['code' => 'IC', 'name' => 'Canary Islands', 'native' => 'islas Canarias'],
        ['code' => 'CV', 'name' => 'Cape Verde', 'native' => 'Kabu Verdi'],
        ['code' => 'BQ', 'name' => 'Caribbean Netherlands', 'native' => ''],
        ['code' => 'KY', 'name' => 'Cayman Islands', 'native' => ''],
        ['code' => 'CF', 'name' => 'Central African Republic', 'native' => 'République centrafricaine'],
        ['code' => 'EA', 'name' => 'Ceuta and Melilla', 'native' => 'Ceuta y Melilla'],
        ['code' => 'TD', 'name' => 'Chad', 'native' => 'Tchad'],
        ['code' => 'CL', 'name' => 'Chile', 'native' => ''],
        ['code' => 'CN', 'name' => 'China', 'native' => '中国'],
        ['code' => 'CX', 'name' => 'Christmas Island', 'native' => ''],
        ['code' => 'CP', 'name' => 'Clipperton Island', 'native' => ''],
        ['code' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'native' => 'Kepulauan Cocos (Keeling)'],
        ['code' => 'CO', 'name' => 'Colombia', 'native' => ''],
        ['code' => 'KM', 'name' => 'Comoros', 'native' => 'جزر القمر'],
        ['code' => 'CD', 'name' => 'Congo (DRC)', 'native' => 'Jamhuri ya Kidemokrasia ya Kongo'],
        ['code' => 'CG', 'name' => 'Congo (Republic)', 'native' => 'Congo-Brazzaville'],
        ['code' => 'CK', 'name' => 'Cook Islands', 'native' => ''],
        ['code' => 'CR', 'name' => 'Costa Rica', 'native' => ''],
        ['code' => 'CI', 'name' => 'Côte d’Ivoire', 'native' => ''],
        ['code' => 'HR', 'name' => 'Croatia', 'native' => 'Hrvatska'],
        ['code' => 'CU', 'name' => 'Cuba', 'native' => ''],
        ['code' => 'CW', 'name' => 'Curaçao', 'native' => ''],
        ['code' => 'CY', 'name' => 'Cyprus', 'native' => 'Κύπρος'],
        ['code' => 'CZ', 'name' => 'Czech Republic', 'native' => 'Česká republika'],
        ['code' => 'DK', 'name' => 'Denmark', 'native' => 'Danmark'],
        ['code' => 'DG', 'name' => 'Diego Garcia', 'native' => ''],
        ['code' => 'DJ', 'name' => 'Djibouti', 'native' => ''],
        ['code' => 'DM', 'name' => 'Dominica', 'native' => ''],
        ['code' => 'DO', 'name' => 'Dominican Republic', 'native' => 'República Dominicana'],
        ['code' => 'EC', 'name' => 'Ecuador', 'native' => ''],
        ['code' => 'EG', 'name' => 'Egypt', 'native' => 'مصر'],
        ['code' => 'SV', 'name' => 'El Salvador', 'native' => ''],
        ['code' => 'GQ', 'name' => 'Equatorial Guinea', 'native' => 'Guinea Ecuatorial'],
        ['code' => 'ER', 'name' => 'Eritrea', 'native' => ''],
        ['code' => 'EE', 'name' => 'Estonia', 'native' => 'Eesti'],
        ['code' => 'ET', 'name' => 'Ethiopia', 'native' => ''],
        ['code' => 'FK', 'name' => 'Falkland Islands', 'native' => 'Islas Malvinas'],
        ['code' => 'FO', 'name' => 'Faroe Islands', 'native' => 'Føroyar'],
        ['code' => 'FJ', 'name' => 'Fiji', 'native' => ''],
        ['code' => 'FI', 'name' => 'Finland', 'native' => 'Suomi'],
        ['code' => 'FR', 'name' => 'France', 'native' => ''],
        ['code' => 'GF', 'name' => 'French Guiana', 'native' => 'Guyane française'],
        ['code' => 'PF', 'name' => 'French Polynesia', 'native' => 'Polynésie française'],
        ['code' => 'TF', 'name' => 'French Southern Territories', 'native' => 'Terres australes françaises'],
        ['code' => 'GA', 'name' => 'Gabon', 'native' => ''],
        ['code' => 'GM', 'name' => 'Gambia', 'native' => ''],
        ['code' => 'GE', 'name' => 'Georgia', 'native' => 'საქართველო'],
        ['code' => 'DE', 'name' => 'Germany', 'native' => 'Deutschland'],
        ['code' => 'GH', 'name' => 'Ghana', 'native' => 'Gaana'],
        ['code' => 'GI', 'name' => 'Gibraltar', 'native' => ''],
        ['code' => 'GR', 'name' => 'Greece', 'native' => 'Ελλάδα'],
        ['code' => 'GL', 'name' => 'Greenland', 'native' => 'Kalaallit Nunaat'],
        ['code' => 'GD', 'name' => 'Grenada', 'native' => ''],
        ['code' => 'GP', 'name' => 'Guadeloupe', 'native' => ''],
        ['code' => 'GU', 'name' => 'Guam', 'native' => ''],
        ['code' => 'GT', 'name' => 'Guatemala', 'native' => ''],
        ['code' => 'GG', 'name' => 'Guernsey', 'native' => ''],
        ['code' => 'GN', 'name' => 'Guinea', 'native' => 'Guinée'],
        ['code' => 'GW', 'name' => 'Guinea-Bissau', 'native' => 'Guiné Bissau'],
        ['code' => 'GY', 'name' => 'Guyana', 'native' => ''],
        ['code' => 'HT', 'name' => 'Haiti', 'native' => ''],
        ['code' => 'HM', 'name' => 'Heard & McDonald Islands', 'native' => ''],
        ['code' => 'HN', 'name' => 'Honduras', 'native' => ''],
        ['code' => 'HK', 'name' => 'Hong Kong', 'native' => '香港'],
        ['code' => 'HU', 'name' => 'Hungary', 'native' => 'Magyarország'],
        ['code' => 'IS', 'name' => 'Iceland', 'native' => 'Ísland'],
        ['code' => 'IN', 'name' => 'India', 'native' => 'भारत'],
        ['code' => 'ID', 'name' => 'Indonesia', 'native' => ''],
        ['code' => 'IR', 'name' => 'Iran', 'native' => 'ایران'],
        ['code' => 'IQ', 'name' => 'Iraq', 'native' => 'العراق'],
        ['code' => 'IE', 'name' => 'Ireland', 'native' => ''],
        ['code' => 'IM', 'name' => 'Isle of Man', 'native' => ''],
        ['code' => 'IL', 'name' => 'Israel', 'native' => 'ישראל'],
        ['code' => 'IT', 'name' => 'Italy', 'native' => 'Italia'],
        ['code' => 'JM', 'name' => 'Jamaica', 'native' => ''],
        ['code' => 'JP', 'name' => 'Japan', 'native' => '日本'],
        ['code' => 'JE', 'name' => 'Jersey', 'native' => ''],
        ['code' => 'JO', 'name' => 'Jordan', 'native' => 'الأردن'],
        ['code' => 'KZ', 'name' => 'Kazakhstan', 'native' => 'Казахстан'],
        ['code' => 'KE', 'name' => 'Kenya', 'native' => ''],
        ['code' => 'KI', 'name' => 'Kiribati', 'native' => ''],
        ['code' => 'XK', 'name' => 'Kosovo', 'native' => 'Kosovë'],
        ['code' => 'KW', 'name' => 'Kuwait', 'native' => 'الكويت'],
        ['code' => 'KG', 'name' => 'Kyrgyzstan', 'native' => 'Кыргызстан'],
        ['code' => 'LA', 'name' => 'Laos', 'native' => 'ລາວ'],
        ['code' => 'LV', 'name' => 'Latvia', 'native' => 'Latvija'],
        ['code' => 'LB', 'name' => 'Lebanon', 'native' => 'لبنان'],
        ['code' => 'LS', 'name' => 'Lesotho', 'native' => ''],
        ['code' => 'LR', 'name' => 'Liberia', 'native' => ''],
        ['code' => 'LY', 'name' => 'Libya', 'native' => 'ليبيا'],
        ['code' => 'LI', 'name' => 'Liechtenstein', 'native' => ''],
        ['code' => 'LT', 'name' => 'Lithuania', 'native' => 'Lietuva'],
        ['code' => 'LU', 'name' => 'Luxembourg', 'native' => ''],
        ['code' => 'MO', 'name' => 'Macau', 'native' => '澳門'],
        ['code' => 'MK', 'name' => 'Macedonia (FYROM)', 'native' => 'Македонија'],
        ['code' => 'MG', 'name' => 'Madagascar', 'native' => 'Madagasikara'],
        ['code' => 'MW', 'name' => 'Malawi', 'native' => ''],
        ['code' => 'MY', 'name' => 'Malaysia', 'native' => ''],
        ['code' => 'MV', 'name' => 'Maldives', 'native' => ''],
        ['code' => 'ML', 'name' => 'Mali', 'native' => ''],
        ['code' => 'MT', 'name' => 'Malta', 'native' => ''],
        ['code' => 'MH', 'name' => 'Marshall Islands', 'native' => ''],
        ['code' => 'MQ', 'name' => 'Martinique', 'native' => ''],
        ['code' => 'MR', 'name' => 'Mauritania', 'native' => 'موريتانيا'],
        ['code' => 'MU', 'name' => 'Mauritius', 'native' => 'Moris'],
        ['code' => 'YT', 'name' => 'Mayotte', 'native' => ''],
        ['code' => 'MX', 'name' => 'Mexico', 'native' => ''],
        ['code' => 'FM', 'name' => 'Micronesia', 'native' => ''],
        ['code' => 'MD', 'name' => 'Moldova', 'native' => 'Republica Moldova'],
        ['code' => 'MC', 'name' => 'Monaco', 'native' => ''],
        ['code' => 'MN', 'name' => 'Mongolia', 'native' => 'Монгол'],
        ['code' => 'ME', 'name' => 'Montenegro', 'native' => 'Crna Gora'],
        ['code' => 'MS', 'name' => 'Montserrat', 'native' => ''],
        ['code' => 'MA', 'name' => 'Morocco', 'native' => 'المغرب'],
        ['code' => 'MZ', 'name' => 'Mozambique', 'native' => 'Moçambique'],
        ['code' => 'MM', 'name' => 'Myanmar (Burma)', 'native' => 'မြန်မာ'],
        ['code' => 'NA', 'name' => 'Namibia', 'native' => 'Namibië'],
        ['code' => 'NR', 'name' => 'Nauru', 'native' => ''],
        ['code' => 'NP', 'name' => 'Nepal', 'native' => 'नेपाल'],
        ['code' => 'NL', 'name' => 'Netherlands', 'native' => 'Nederland'],
        ['code' => 'NC', 'name' => 'New Caledonia', 'native' => 'Nouvelle-Calédonie'],
        ['code' => 'NZ', 'name' => 'New Zealand', 'native' => ''],
        ['code' => 'NI', 'name' => 'Nicaragua', 'native' => ''],
        ['code' => 'NE', 'name' => 'Niger', 'native' => 'Nijar'],
        ['code' => 'NG', 'name' => 'Nigeria', 'native' => ''],
        ['code' => 'NU', 'name' => 'Niue', 'native' => ''],
        ['code' => 'NF', 'name' => 'Norfolk Island', 'native' => ''],
        ['code' => 'MP', 'name' => 'Northern Mariana Islands', 'native' => ''],
        ['code' => 'KP', 'name' => 'North Korea', 'native' => '조선 민주주의 인민 공화국'],
        ['code' => 'NO', 'name' => 'Norway', 'native' => 'Norge'],
        ['code' => 'OM', 'name' => 'Oman', 'native' => 'عُمان'],
        ['code' => 'PK', 'name' => 'Pakistan', 'native' => 'پاکستان'],
        ['code' => 'PW', 'name' => 'Palau', 'native' => ''],
        ['code' => 'PS', 'name' => 'Palestine', 'native' => 'فلسطين'],
        ['code' => 'PA', 'name' => 'Panama', 'native' => ''],
        ['code' => 'PG', 'name' => 'Papua New Guinea', 'native' => ''],
        ['code' => 'PY', 'name' => 'Paraguay', 'native' => ''],
        ['code' => 'PE', 'name' => 'Peru', 'native' => 'Perú'],
        ['code' => 'PH', 'name' => 'Philippines', 'native' => ''],
        ['code' => 'PN', 'name' => 'Pitcairn Islands', 'native' => ''],
        ['code' => 'PL', 'name' => 'Poland', 'native' => 'Polska'],
        ['code' => 'PT', 'name' => 'Portugal', 'native' => ''],
        ['code' => 'PR', 'name' => 'Puerto Rico', 'native' => ''],
        ['code' => 'QA', 'name' => 'Qatar', 'native' => 'قطر'],
        ['code' => 'RE', 'name' => 'Réunion', 'native' => 'La Réunion'],
        ['code' => 'RO', 'name' => 'Romania', 'native' => 'România'],
        ['code' => 'RU', 'name' => 'Russia', 'native' => 'Россия'],
        ['code' => 'RW', 'name' => 'Rwanda', 'native' => ''],
        ['code' => 'BL', 'name' => 'Saint Barthélemy', 'native' => 'Saint-Barthélemy'],
        ['code' => 'SH', 'name' => 'Saint Helena', 'native' => ''],
        ['code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'native' => ''],
        ['code' => 'LC', 'name' => 'Saint Lucia', 'native' => ''],
        ['code' => 'MF', 'name' => 'Saint Martin', 'native' => ''],
        ['code' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'native' => 'Saint-Pierre-et-Miquelon'],
        ['code' => 'WS', 'name' => 'Samoa', 'native' => ''],
        ['code' => 'SM', 'name' => 'San Marino', 'native' => ''],
        ['code' => 'ST', 'name' => 'São Tomé and Príncipe', 'native' => 'São Tomé e Príncipe'],
        ['code' => 'SA', 'name' => 'Saudi Arabia', 'native' => 'المملكة العربية السعودية'],
        ['code' => 'SN', 'name' => 'Senegal', 'native' => 'Sénégal'],
        ['code' => 'RS', 'name' => 'Serbia', 'native' => 'Србија'],
        ['code' => 'SC', 'name' => 'Seychelles', 'native' => ''],
        ['code' => 'SL', 'name' => 'Sierra Leone', 'native' => ''],
        ['code' => 'SG', 'name' => 'Singapore', 'native' => ''],
        ['code' => 'SX', 'name' => 'Sint Maarten', 'native' => ''],
        ['code' => 'SK', 'name' => 'Slovakia', 'native' => 'Slovensko'],
        ['code' => 'SI', 'name' => 'Slovenia', 'native' => 'Slovenija'],
        ['code' => 'SB', 'name' => 'Solomon Islands', 'native' => ''],
        ['code' => 'SO', 'name' => 'Somalia', 'native' => 'Soomaaliya'],
        ['code' => 'ZA', 'name' => 'South Africa', 'native' => ''],
        ['code' => 'GS', 'name' => 'South Georgia & South Sandwich Islands', 'native' => ''],
        ['code' => 'KR', 'name' => 'South Korea', 'native' => '대한민국'],
        ['code' => 'SS', 'name' => 'South Sudan', 'native' => 'جنوب السودان'],
        ['code' => 'ES', 'name' => 'Spain', 'native' => 'España'],
        ['code' => 'LK', 'name' => 'Sri Lanka', 'native' => 'ශ්‍රී ලංකාව'],
        ['code' => 'VC', 'name' => 'St. Vincent & Grenadines', 'native' => ''],
        ['code' => 'SD', 'name' => 'Sudan', 'native' => 'السودان'],
        ['code' => 'SR', 'name' => 'Suriname', 'native' => ''],
        ['code' => 'SJ', 'name' => 'Svalbard and Jan Mayen', 'native' => 'Svalbard og Jan Mayen'],
        ['code' => 'SZ', 'name' => 'Swaziland', 'native' => ''],
        ['code' => 'SE', 'name' => 'Sweden', 'native' => 'Sverige'],
        ['code' => 'CH', 'name' => 'Switzerland', 'native' => 'Schweiz'],
        ['code' => 'SY', 'name' => 'Syria', 'native' => 'سوريا'],
        ['code' => 'TW', 'name' => 'Taiwan', 'native' => '台灣'],
        ['code' => 'TJ', 'name' => 'Tajikistan', 'native' => ''],
        ['code' => 'TZ', 'name' => 'Tanzania', 'native' => ''],
        ['code' => 'TH', 'name' => 'Thailand', 'native' => 'ไทย'],
        ['code' => 'TL', 'name' => 'Timor-Leste', 'native' => ''],
        ['code' => 'TG', 'name' => 'Togo', 'native' => ''],
        ['code' => 'TK', 'name' => 'Tokelau', 'native' => ''],
        ['code' => 'TO', 'name' => 'Tonga', 'native' => ''],
        ['code' => 'TT', 'name' => 'Trinidad and Tobago', 'native' => ''],
        ['code' => 'TA', 'name' => 'Tristan da Cunha', 'native' => ''],
        ['code' => 'TN', 'name' => 'Tunisia', 'native' => 'تونس'],
        ['code' => 'TR', 'name' => 'Turkey', 'native' => 'Türkiye'],
        ['code' => 'TM', 'name' => 'Turkmenistan', 'native' => ''],
        ['code' => 'TC', 'name' => 'Turks and Caicos Islands', 'native' => ''],
        ['code' => 'TV', 'name' => 'Tuvalu', 'native' => ''],
        ['code' => 'UM', 'name' => 'U.S. Outlying Islands', 'native' => ''],
        ['code' => 'VI', 'name' => 'U.S. Virgin Islands', 'native' => ''],
        ['code' => 'UG', 'name' => 'Uganda', 'native' => ''],
        ['code' => 'UA', 'name' => 'Ukraine', 'native' => 'Україна'],
        ['code' => 'AE', 'name' => 'United Arab Emirates', 'native' => 'الإمارات العربية المتحدة'],
        ['code' => 'GB', 'name' => 'United Kingdom', 'native' => ''],
        ['code' => 'US', 'name' => 'United States', 'native' => ''],
        ['code' => 'UY', 'name' => 'Uruguay', 'native' => ''],
        ['code' => 'UZ', 'name' => 'Uzbekistan', 'native' => 'Oʻzbekiston'],
        ['code' => 'VU', 'name' => 'Vanuatu', 'native' => ''],
        ['code' => 'VA', 'name' => 'Vatican City', 'native' => 'Città del Vaticano'],
        ['code' => 'VE', 'name' => 'Venezuela', 'native' => ''],
        ['code' => 'VN', 'name' => 'Vietnam', 'native' => 'Việt Nam'],
        ['code' => 'WF', 'name' => 'Wallis and Futuna', 'native' => ''],
        ['code' => 'EH', 'name' => 'Western Sahara', 'native' => 'الصحراء الغربية'],
        ['code' => 'YE', 'name' => 'Yemen', 'native' => 'اليمن'],
        ['code' => 'ZM', 'name' => 'Zambia', 'native' => ''],
        ['code' => 'ZW', 'name' => 'Zimbabwe', 'native' => '']
    ];
    /**
     * United States - States + Code
     *
     * @var array
     */
    protected $US_states = [
        ['code' => 'AL', 'name' => 'Alabama'],
        ['code' => 'AK', 'name' => 'Alaska'],
        ['code' => 'AS', 'name' => 'American Samoa'],
        ['code' => 'AZ', 'name' => 'Arizona'],
        ['code' => 'AR', 'name' => 'Arkansas'],
        ['code' => 'CA', 'name' => 'California'],
        ['code' => 'CO', 'name' => 'Colorado'],
        ['code' => 'CT', 'name' => 'Connecticut'],
        ['code' => 'DE', 'name' => 'Delaware'],
        ['code' => 'DC', 'name' => 'Dist. of Columbia'],
        ['code' => 'FL', 'name' => 'Florida'],
        ['code' => 'GA', 'name' => 'Georgia'],
        ['code' => 'GU', 'name' => 'Guam'],
        ['code' => 'HI', 'name' => 'Hawaii'],
        ['code' => 'ID', 'name' => 'Idaho'],
        ['code' => 'IL', 'name' => 'Illinois'],
        ['code' => 'IN', 'name' => 'Indiana'],
        ['code' => 'IA', 'name' => 'Iowa'],
        ['code' => 'KS', 'name' => 'Kansas'],
        ['code' => 'KY', 'name' => 'Kentucky'],
        ['code' => 'LA', 'name' => 'Louisiana'],
        ['code' => 'ME', 'name' => 'Maine'],
        ['code' => 'MD', 'name' => 'Maryland'],
        ['code' => 'MH', 'name' => 'Marshall Islands'],
        ['code' => 'MA', 'name' => 'Massachusetts'],
        ['code' => 'MI', 'name' => 'Michigan'],
        ['code' => 'FM', 'name' => 'Micronesia'],
        ['code' => 'MN', 'name' => 'Minnesota'],
        ['code' => 'MS', 'name' => 'Mississippi'],
        ['code' => 'MO', 'name' => 'Missouri'],
        ['code' => 'MT', 'name' => 'Montana'],
        ['code' => 'NE', 'name' => 'Nebraska'],
        ['code' => 'NV', 'name' => 'Nevada'],
        ['code' => 'NH', 'name' => 'New Hampshire'],
        ['code' => 'NJ', 'name' => 'New Jersey'],
        ['code' => 'NM', 'name' => 'New Mexico'],
        ['code' => 'NY', 'name' => 'New York'],
        ['code' => 'NC', 'name' => 'North Carolina'],
        ['code' => 'ND', 'name' => 'North Dakota'],
        ['code' => 'MP', 'name' => 'Northern Marianas'],
        ['code' => 'OH', 'name' => 'Ohio'],
        ['code' => 'OK', 'name' => 'Oklahoma'],
        ['code' => 'OR', 'name' => 'Oregon'],
        ['code' => 'PW', 'name' => 'Palau'],
        ['code' => 'PA', 'name' => 'Pennsylvania'],
        ['code' => 'PR', 'name' => 'Puerto Rico'],
        ['code' => 'RI', 'name' => 'Rhode Island'],
        ['code' => 'SC', 'name' => 'South Carolina'],
        ['code' => 'SD', 'name' => 'South Dakota'],
        ['code' => 'TN', 'name' => 'Tennessee'],
        ['code' => 'TX', 'name' => 'Texas'],
        ['code' => 'UT', 'name' => 'Utah'],
        ['code' => 'VT', 'name' => 'Vermont'],
        ['code' => 'VA', 'name' => 'Virginia'],
        ['code' => 'VI', 'name' => 'Virgin Islands'],
        ['code' => 'WA', 'name' => 'Washington'],
        ['code' => 'WV', 'name' => 'West Virginia'],
        ['code' => 'WI', 'name' => 'Wisconsin'],
        ['code' => 'WY', 'name' => 'Wyoming']
    ];
    /**
     * Canada - States + Code
     *
     * @var array
     */
    protected $CA_States = [
        ['code' => 'AB', 'name' => 'Alberta'],
        ['code' => 'BC', 'name' => 'British Columbia'],
        ['code' => 'MB', 'name' => 'Manitoba'],
        ['code' => 'NB', 'name' => 'New Brunswick'],
        ['code' => 'NL', 'name' => 'Newfoundland and Labrador'],
        ['code' => 'NT', 'name' => 'Northwest Territories'],
        ['code' => 'NS', 'name' => 'Nova Scotia'],
        ['code' => 'NU', 'name' => 'Nunavut'],
        ['code' => 'ON', 'name' => 'Ontario'],
        ['code' => 'PE', 'name' => 'Prince Edward Island'],
        ['code' => 'QC', 'name' => 'Quebec'],
        ['code' => 'SK', 'name' => 'Saskatchewan'],
        ['code' => 'YT', 'name' => 'Yukon']
    ];
    /**
     * Australia - States + Code
     * 
     * @var array
     */
    protected $AU_States = [
        ['code' => 'NSW', 'name' => 'New South Wales'],
        ['code' => 'QLD', 'name' => 'Queensland'],
        ['code' => 'SA', 'name' => 'South Australia'],
        ['code' => 'TAS', 'name' => 'Tasmania'],
        ['code' => 'VIC', 'name' => 'Victoria'],
        ['code' => 'WA', 'name' => 'Western Australia'],
        ['code' => 'NT', 'name' => 'Northern Territory'],
        ['code' => 'ACT', 'name' => 'Australian Capital Territory']
    ];

    /**
     * Country constructor.
     * @param $label
     * @param array $attributes
     */
    public function __construct($label, array $attributes = [])
    {
        $Options = [];
        foreach($this->CountriesDatas as $data)
        {
            $Options[$data['code']] = $data['name'];
            empty($data['native']) OR $Options[$data['code']] .= ', ('.$data['native'].')';
        }
        parent::__construct($label, $Options, $attributes);
        $this->Attributes()->set('placeholder','Choose a country...');
    }

}